### ISSUE TITLE
Change the API of find_pairs function

### ISSUE THREAD

**Issue by k32** [kafka4beam/snabbkaffe#25]
Currently this function accepts `Strict` flag that causes it throw an exception when it encounters an unmatched effect. However, for unmatched causes it returns a singleton tuple. This makes this API asymmetric. 
Strict flag should be dropped, and this function should not throw exceptions and always return a list of following tuples:
```erlang
-type pair() :: {pair, _, _} | {unmatched_cause, _} | {unmatched_effect, _}.
```

Causality macros should take care of throwing exceptions when `{unmatched_effect, _}` is found.

**Comment by qzhuyan** [comment]
great!

what about ordering? There will be a flag to control the order check?

**Comment by k32** [comment]
The order check will happen in causality and strict causality functions. They'll just have to check that there is no `{unmatched_effect, ...}` tuples in the list
