### ISSUE TITLE
Not compiling: 'ct_slave:start/2' deprecated OTP-25

### ISSUE THREAD

**Issue by machist** [kafka4beam/snabbkaffe#53]
Here is what I get with OTP-25:

````shell
===> Compiling test/remote_SUITE.erl failed
test/remote_SUITE.erl:118:3: ct_slave:start/2 is deprecated and will be removed in OTP 27; use ?CT_PEER(), or the 'peer' module instead

make: *** [Makefile:12: all] Error 1
````

**Comment by machist** [comment]
Will try to fix it using
https://www.erlang.org/doc/man/peer.html#example

**Comment by ieQu1** [comment]
Awesome, thanks. I noticed this bug as well, and just silenced the warning, but a proper solution is welcom. https://github.com/kafka4beam/snabbkaffe/pull/54

**Comment by ieQu1** [comment]
Version `1.0.5` contains the preliminary fix that silences the warnings.

**Comment by machist** [comment]
Thanks :)
